version: '3.8'
 
services:
  api:
    build:
      context: ./server/php
    ports:
      - "8080:80"
    depends_on:
      - mysql
      
  nodejs:
    build:
      context: ./server/nodejs
    ports:
      - "5000:5000"
 
  mysql:
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: instagram-clone
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
 
  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"  # Adjust the port as needed
    depends_on:
      - api
      - nodejs