version: '3.8'
 
services:
  php:
    build:
      context: ./server/php
    ports:
      - "8080:80"
      
  nodejs:
    build:
      context: ./server/nodejs
    ports:
      - "5000:5000"
 
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"  # Adjust the port as needed
    depends_on:
      - php
      - nodejs