# Use an official MySQL image as the base image
FROM mysql:latest
 
# Set the root password and create a database
ENV MYSQL_ROOT_PASSWORD=123456
ENV MYSQL_DATABASE=instagram-clone
 
# Optionally, expose the MySQL port
EXPOSE 3306